name: Automated Test on Android

on: [push]

jobs:
  dependencies:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
  test:
    runs-on: [self-hosted, linux]
    needs: dependencies
    steps:
      - name: Run the tests
        run: npx wdio
  upload_artifacts:
    runs-on: [self-hosted, linux]
    needs: test
    steps:
      - name: Generate the report
        run: allure generate --single-file
      - name: Zip the report file
        run: zip -j testResults.zip allure-report/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: testResults.zip
