name: Automated Test on Android

on: [push]

jobs:
  dependencies:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci

  test:
    runs-on: [self-hosted, linux]
    needs: dependencies
    steps:
      - name: Run the tests
        run: npx wdio | cut -c -512

  upload_artifacts:
    if: ${{ always() }}
    runs-on: [self-hosted, linux]
    needs: test
    steps:
      - name: Generate the report
        run: allure generate
      - name: Zip the report file
        run: zip -r allure-report.zip allure-report/*
      - uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: allure-report.zip
